SklepInternetowy.WWW/Controllers/SklepController.cs
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.WWW.Models;
using SklepInternetowy.WWW.Services.DataStore;
using System.Diagnostics;
using SklepInternetowy.WWW.Models.ViewModels;
using SklepInternetowyServiceReference;

namespace SklepInternetowy.WWW.Controllers
{
    public class SklepController : Controller
    {
        private readonly ILogger<SklepController> _logger;
        private readonly TowaryDataStore _dataStore;

        public SklepController(ILogger<SklepController> logger,TowaryDataStore dataStore)
        {
            _logger = logger;
            _dataStore = dataStore;
        }

        public IActionResult Sklep()
        {
            try
            {
                var towary = _dataStore.items.ToList();
                return View(towary);
            }
            catch (Exception)
            {
                Console.WriteLine("Wystapil blad podczas pobierania produktow");
                return View();
            }
        }

        public async Task<IActionResult> OtworzSzczegoly(int id)
        {
            return RedirectToAction("ProduktDetail", new { id = id });
        }

        public async Task<ActionResult> ProduktDetail(int id)
        {
            try
            {
                var towar = _dataStore.Find(id);
                return View(towar);
            }
            catch (Exception)
            {
                Console.WriteLine("Wystapil blad podczas pobierania produktow");
                return View();
            }
        }

        public IActionResult DodajProdukt()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DodajProdukt(DodajProduktViewModel produktViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(produktViewModel);
            }
            var towar = new Towar()
            {
                Nazwa = produktViewModel.Nazwa,
                Kod = produktViewModel.Kod,
                IdKategorii = produktViewModel.IdKategorii,
                Cena = produktViewModel.Cena,
                NaStanie = produktViewModel.NaStanie,
                ZdjecieUrl = produktViewModel.ZdjecieUrl,
                Opis = produktViewModel.Opis
            };
            
            if (towar != null)
            {
                await _dataStore.AddItemToService(towar);
            }
            return RedirectToAction(nameof(Sklep));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SklepInternetowy.WWW/Controllers/ZamowieniaController.cs
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.WWW.Models;
using SklepInternetowy.WWW.Models.Services.DataStore;
using SklepInternetowy.WWW.Services;
using SklepInternetowy.WWW.Services.DataStore;
using SklepInternetowy.WWWW.Services.DataStore;
using SklepInternetowyServiceReference;
using System.Diagnostics;
using SklepInternetowy.WWW.Extensions;

namespace SklepInternetowy.WWW.Controllers
{
    public class ZamowieniaController : Controller
    {
        private readonly ILogger<ZamowieniaController> _logger;
        private readonly ZamowienieDataStore _dataStore;
        private readonly TowarZamowieniaDataStore _dataStoreTowarZamowienia;
        private readonly ElementKoszykaDataStore _dataStoreElementKoszyka;
        private readonly KodPromocjiDataStore _kodPromocjiDataStore;
        
        public ZamowieniaController(TowarZamowieniaDataStore dataStoreTowarZamowienia, ElementKoszykaDataStore dataStoreElementKoszyka, KodPromocjiDataStore kodPromocjiDataStore, ZamowienieDataStore dataStore, ILogger<ZamowieniaController> logger)
        {
            _dataStoreTowarZamowienia = dataStoreTowarZamowienia;
            _dataStoreElementKoszyka = dataStoreElementKoszyka;
            _kodPromocjiDataStore = kodPromocjiDataStore;
            _dataStore = dataStore;
            _logger = logger;
        }

        public IActionResult Zamowienia()
        {
            try
            {
                var zamowienia = _dataStore.items.ToList();
                return View(zamowienia);
            }
            catch (Exception)
            {
                Console.WriteLine("Wystapil blad podczas pobierania produktow");
                return View();
            }
        }

        public async Task<ActionResult> OtworzSzczegoly(int id)
        {
            return RedirectToAction("ZamowienieDetail", new { id = id });
        }    
        
        public async Task<ActionResult> ZamowienieMessage()
        {
            return View();
        }   

        public async Task<ActionResult> ZamowienieDetail(int id)
        {
            try
            {
                var orderItems = _dataStoreTowarZamowienia.items
                    .Where(a => a.IdZamowienia == id)
                    .ToList();

                return View(orderItems);
            }
            catch (Exception)
            {
                Console.WriteLine("Wystapil blad podczas pobierania produktow");
                return View();
            }
        }

        public async Task<ActionResult> ZlozZamowienie()
        {

            try
            {
                //create order
                Zamowienie zamowienie = new Zamowienie();

                //check if there is available promotions code
                if (CartService.IdKoduPromocji != null)
                {
                    zamowienie.IdKoduPromocji = CartService.IdKoduPromocji;
                }
              

                var addedOrder = await _dataStore.AddItemToService(zamowienie);

                if (addedOrder == null)
                {
                    Console.WriteLine("Failed to add a new order.");
                    RedirectToAction("Zamowienia"); ;
                }

                //create OrderItems
                var items = await _dataStoreElementKoszyka.GetItemsAsync(true);
                foreach (var item in items)
                {
                    TowarZamowienium towarZamowienia = new TowarZamowienium();
                    var addedOrderItem = await _dataStoreTowarZamowienia.AddItemAsync(towarZamowienia);
                    Console.WriteLine("Ordrer added");

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
            CartService.Znizka = null;
            return RedirectToAction("ZamowienieMessage");
        }

        public async Task<ActionResult> DodajKodRabatowy(string kod)
        {
            var kodPromocyjnyResponse = await _kodPromocjiDataStore.GetZnizka(kod);

            CartService.Znizka = kodPromocyjnyResponse.Znizka;
            CartService.IdKoduPromocji = kodPromocyjnyResponse.IdKoduPromocji;
            this.SetNotification("Discount applied!");
            return RedirectToAction("Koszyk", "Koszyk");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SklepInternetowy.WWW/Views/Zamowienia/Zamowienia.cshtml
@model List<Zamowienie>
@using SklepInternetowyServiceReference

@{
    ViewData["Title"] = "Moje Zamowienia";
}

<style>

    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }

    .background-transient {
        background-color: rgba(255, 255, 255, 0.6);
    }

    .list-group {
        box-shadow: none;
    }

    .button-link {
        display: inline-block;
        background: #3498db;
        color: #fff;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background 0.3s ease;
        margin-top: 10px;
        font-weight: 600;
    }

        .button-link:hover {
            background: #2980b99c;
            color: #fff;
            font-weight: 600;
        }

    .background-gardient {
        background: linear-gradient(to right, #f0f0f0, #fff);
    }

</style>
<div class="card p-5 background-transient">
    <div class="container">
        <div class="row mt-3">
            <a class="col-2 text-dark fw-bold mb-4 btn btn-warning" asp-area="" asp-controller="Sklep" asp-action="Sklep">Wroc do sklepu</a>
        </div>
    </div>

 
    <div class="card p-4">
        <div class="text-center mb-3">
            <h3 class="display-4">Moje Zamowienia</h3>
        </div>
        <div id="cartContent" class="container pe-lg-5">
        @if (Model.Count > 0)
        {
            <ul class="list-group container">
                @foreach (var zamowienie in Model)
                {
                    <li class="list-group-item background-gardient mb-4">
                        <div class="background-gardient">
                            <div class="background-gardient">
                                <h5 class="card-title">Data zlozenia: @zamowienie.DataZamowienia</h5>
                                <p class="card-text">Numer zamowienia: @zamowienie.IdZamowienia</p>
                                <p class="card-text">Wartosc lacznie: @zamowienie.Suma €</p>
                                <p class="card-text">Przewidywany termin dostawy: @zamowienie.TerminDostawy</p>
                            </div>
                            <a asp-action="OtworzSzczegoly" asp-controller="Zamowienia" asp-route-id="@zamowienie.IdZamowienia" class="button-link">Szczegoly...</a>
                        </div>

                    </li>

                }
            </ul>
        }
        else
        {
            <div class="text-center">
                <p>Nie masz zadnych zamowien!</p>
            </div>
        }
    </div>
    </div>

</div>

SklepInternetowy.WWW/Views/Zamowienia/ZamowienieDetail.cshtml
@model List<TowarZamowienium>

@using SklepInternetowyServiceReference
@{
    ViewData["Title"] = "Szczegoly zamowienia";
}

<style>

    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }

    .background-transient {
        background-color: rgba(255, 255, 255, 0.6);
    }

    .list-group {
        box-shadow: none;
    }
    .card-img {
        object-fit: contain;
        max-height: 400px;
        max-width: 100%;
    }
</style>

<div class="card p-5 background-transient text-center">
    <div class="container">
        <div class="row mt-3 mb-3">
            <a class="col-2 text-dark fw-bold mb-4 btn btn-warning" asp-area="" asp-controller="Zamowienia" asp-action="Zamowienia">Wroc do listy zamowien</a>
        </div>
    </div>
    <div class="card p-4">    
        <div class="text-center">
            <h4 class="display-4 mb-4 mt-4 pe-lg-0">Produkty znajdujace sie w zamowieniu: </h4>
        </div>

        <div id="cartContent" class="container pe-lg-5">
        <ul class="list-group container">
            @foreach (var produkt in Model)
            {
                <li class="list-group-item background-gardient mb-2">
                    <div class=" background-gardient">
                        <div class="background-gardient">
                            <p class="card-title">@produkt.NazwaTowaru</p>
                            <p class="card-text">Ilość: @produkt.Ilosc</p>
                            <p class="card-text">Cena za sztuke: @produkt.Cena €</p>
                        </div>
                    </div>
                </li>
            }
         </ul>
        </div>
    </div>

</div>

SklepInternetowy.WWW/Views/Zamowienia/ZamowienieMessage.cshtml
@model List<TowarZamowienium>

@using SklepInternetowyServiceReference
@{
    ViewData["Title"] = "Szczegoly zamowienia";
}

<style>
    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }

    .background-transient {
        background-color: rgba(255, 255, 255, 0.6);
    }
</style>

<div class="card background-transient p-5">
    <div class="container">
        <div class="row mt-3 mb-3">
            <a class="col-2 text-dark fw-bold mb-4 btn btn-warning" asp-area="" asp-controller="Sklep" asp-action="Sklep">Wroc do sklepu</a>
        </div>
    </div>

    <div class="text-center mt-5">
        <h4 class="display-4 mb-5">Dziekujemy za zlozenie zamowienia!</h4>
    </div>
    <div class="card text-center">
        <p class="mb-4 mt-4"> Potwierdzenie zostalo wyslany na Twoj adres E-mail!</p>
        <p class="mb-4"> Przejdz do zakladki "Moje zamowienia" by w kazdej chwili sprawdzic status Twoich zamowien!</p>
    </div>
</div>