SklepInternetowy.WWW/Controllers/KontoController.cs
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.WWW.Models;
using System.Diagnostics;
using System.Net.Http.Headers;
using SklepInternetowy.WWW.Extensions;
using SklepInternetowy.WWW.Models.Services.DataStore;
using SklepInternetowy.WWW.Services;
using SklepInternetowyServiceReference;

namespace SklepInternetowy.WWW.Controllers
{
    public class KontoController : Controller
    {
        private readonly ILogger<KontoController> _logger;
        private readonly UserService _userService;
        private readonly UzytkownikDataStore _uzytkownikDataStore;
        private readonly SklepInternetowyService _sklepInternetowyService;
        public KontoController(ILogger<KontoController> logger, UserService userService, UzytkownikDataStore uzytkownikDataStore)
        {
            _logger = logger;
            _userService = userService;
            _uzytkownikDataStore = uzytkownikDataStore;
            
            var httpClient = new HttpClient();
            
            if (_userService.Token != null)
            {
                httpClient.DefaultRequestHeaders.Authorization =
                    new AuthenticationHeaderValue("Bearer", _userService.Token);
            }
            
            _sklepInternetowyService = new SklepInternetowyService("http://localhost:5219/", httpClient);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Konto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _userService.Logout();
            return RedirectToAction(nameof(Index), nameof(Konto));
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            if (ModelState.IsValid)
            {
                var jwtStorage = await _sklepInternetowyService.LoginAsync(loginDto);
                if (jwtStorage != null)
                {
                    //TODO prolly there's better way to store secrets
                    _userService.Token = jwtStorage.Jwt;
                    _userService.DecodeJwt();
                }
            }
            
            this.SetNotification("Successfully logged in!");
            
            return RedirectToAction("Sklep", "Sklep");
        }
        
        public IActionResult Register()
        {
            return View(nameof(Register));
        }
        
        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserDto registerUserDto)
        {
            if (ModelState.IsValid)
            {
                await _sklepInternetowyService.RegisterAsync(registerUserDto);
            }
            return RedirectToAction(nameof(Login));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SklepInternetowy.WWW/Views/Konto/Index.cshtml
@{
    ViewData["Title"] = "Login";
}

<style>
    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }

    .background-transient {
        background-color: rgba(255, 255, 255, 0.6);
    }
</style>

<div class="card p-5 background-transient text-center text">
    <h1 class="display-4">Witamy!</h1>
    <br />
    <div class="card">
        <p class="fw-bold mb-4 mt-4">Aby rozpoczac zaloguj sie lub zarejestruj!</p>
        <p> wojtek@wojtek.pl wojtek - user</p>
        <p> pati@pati.pl - pati - admin</p>
    </div>
</div>

SklepInternetowy.WWW/Views/Konto/Konto.cshtml
@{
    ViewData["Title"] = "Moje konto";
}
<style>

    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }

    .background-transient {
        background-color: rgba(255, 255, 255, 0.6);
    }

</style>

<div class="card p-5 background-transient">
    <div class="card p-3 pt-4">

     <div class="text-center">
        <h1 class="display-4 mb-4 mt-4">Moje konto</h1>
     </div>

        <div class="container">
            <div class="row">
                <a class="btn btn-light col-12 mt-4 fw-bold" asp-area="" asp-controller="Konto" asp-action="Konto" title="Manage">Moje zamowienia</a>
                <a class="btn btn-light col-12 mt-4 fw-bold" asp-area="" asp-controller="Konto" asp-action="Konto" title="Manage">Moje dane</a>
            </div>
        </div>
    </div>
</div>


@* <li class="nav-item"> *@
@*     <a class="nav-link text-dark" asp-area="" asp-controller="Zamowienia" asp-action="Zamowienia">Moje zamowienia</a> *@
@* </li> *@
@* <li class="nav-item"> *@
@*     <a class="nav-link text-dark" asp-area="" asp-controller="Konto" asp-action="Konto">Moje konto</a> *@
@* </li> *@

SklepInternetowy.WWW/Views/Konto/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
<style>
    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Login</div>
                <div class="card-body">
                    <form asp-action="Login" method="post">
                        <div class="form-group">
                            <label for="Email">Email:</label>
                            <input type="email" class="form-control mb-2" id="Email" name="Email" required />
                        </div>
                        <div class="form-group">
                            <label for="Password">Password:</label>
                            <input type="password" class="form-control" id="Password" name="Password" required />
                        </div>
                        <button type="submit" class="btn btn-primary mt-4">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

SklepInternetowy.WWW/Views/Konto/Register.cshtml
@{
    ViewData["Title"] = "Register";
}
<style>
    body {
        background: url('https://tse2.mm.bing.net/th?id=OIP.xo7kJ5SSq8_ecPGLwiyUuAHaET&pid=Api&P=0&h=220');
        background-size: cover;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <form asp-action="Register" method="post">
                        <div class="form-group">
                            <label>Imie:</label>
                            <input class="form-control" id="Imie" name="Imie" required/>
                        </div>
                        <div class="form-group">
                            <label>Nazwisko:</label>
                            <input class="form-control" id="Nazwisko" name="Nazwisko" required/>
                        </div>
                        <div class="form-group">
                            <label for="Email">Email:</label>
                            <input type="email" class="form-control" id="Email" name="Email" required/>
                        </div>
                        <div class="form-group">
                            <label for="Password">Password:</label>
                            <input type="password" class="form-control" id="Password" name="Password" required/>
                        </div>
                        <div class="form-group">
                            <label for="ConfirmPassword">Confirm Password:</label>
                            <input type="password" class="form-control" id="ConfirmPassword" name="ConfirmPassword" required/>
                        </div>
                        <button type="submit" class="btn btn-info mt-3">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>